apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strapi-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/cyrixrr/devops-final.git
    targetRevision: main
    path: gitops/apps/strapi/chart
    helm:
      releaseName: strapi-dev
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: strapi-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
